// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hxnnbsqP29q_PvREJg_rc59EQOX8Xd0',
    appId: '1:573566316347:web:3bb397f5ab8b8a893f911e',
    messagingSenderId: '573566316347',
    projectId: 'fir-first-app-5a033',
    authDomain: 'fir-first-app-5a033.firebaseapp.com',
    storageBucket: 'fir-first-app-5a033.appspot.com',
    measurementId: 'G-1CHGTZ1CXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIOSVtDROswm91UIvrK0sa57HOAhzkkdI',
    appId: '1:573566316347:android:31e6e21e48bc011d3f911e',
    messagingSenderId: '573566316347',
    projectId: 'fir-first-app-5a033',
    storageBucket: 'fir-first-app-5a033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6oDG06Zl9GST92qvJAkzin8v114RmtY',
    appId: '1:573566316347:ios:d5b8603e283a15ef3f911e',
    messagingSenderId: '573566316347',
    projectId: 'fir-first-app-5a033',
    storageBucket: 'fir-first-app-5a033.appspot.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6oDG06Zl9GST92qvJAkzin8v114RmtY',
    appId: '1:573566316347:ios:d5b8603e283a15ef3f911e',
    messagingSenderId: '573566316347',
    projectId: 'fir-first-app-5a033',
    storageBucket: 'fir-first-app-5a033.appspot.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1hxnnbsqP29q_PvREJg_rc59EQOX8Xd0',
    appId: '1:573566316347:web:0691fb6053fb878b3f911e',
    messagingSenderId: '573566316347',
    projectId: 'fir-first-app-5a033',
    authDomain: 'fir-first-app-5a033.firebaseapp.com',
    storageBucket: 'fir-first-app-5a033.appspot.com',
    measurementId: 'G-N32SF9PEDM',
  );
}
